version: '2'
services:
  rest-api:
    links:
      - "db:db"
    image: pagekb/golang-gin
    volumes:
      - ./rest-api:/go/src/dockerized-go-app/rest-api:ro
    command: gin -t /go/src/dockerized-go-app/rest-api
    ports:
      - 3000:3000
    environment:
      - DB_USERNAME=restbucks
      - DB_PASSWORD=restbucks
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=restbucks
      - LOGXI=*
  rest-api-integration-tester:
    build: ./rest-api-integration-tester
    volumes:
      - ./rest-api:/go/src/dockerized-go-app/rest-api
    links:
      - rest-api
  db:
    image: mariadb:10.1.16
    environment:
      - MYSQL_ROOT_PASSWORD=rewt
      - MYSQL_DATABASE=restbucks
      - MYSQL_USER=restbucks
      - MYSQL_PASSWORD=restbucks
      - LANG=C.UTF-8
    ports:
# Linked containers will use standard db port, but exposing as 3336 on host to avoid conflicting with
# other existing DB that may be installed
      - 3336:3306
  db-migrations:
    image: pagekb/docker-flyway
    command: ./wait-for-it.sh db:3306 -s -- flyway -url=jdbc:mysql://db -schemas=restbucks -user=root -password=rewt migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - db
  web-client:
    build: ./web-client
    user: node
    ports:
      - 4000:4000
    volumes:
      - ./web-client:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - rest-api